데이터 수집: 크롤링

In [1]:
import san

bitcoin = san.get("ohlcv/bitcoin") # open,high,low,close,volume

In [4]:
bitcoin.head(1) # 가장 맨 위에 있는 값 뽑기

,openPriceUsd,closePriceUsd,highPriceUsd,lowPriceUsd,volume,marketcap
datetime,,,,,,
2021-09-14 00:00:00+00:00,46732.444869,47092.493833,47213.518594,46210.873623,3.865215e+10,8.860953e+11

In [6]:
bitcoin.info() # Dataframe의 정보

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 366 entries, 2021-09-14 00:00:00+00:00 to 2022-09-14 00:00:00+00:00
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   openPriceUsd   366 non-null    float64
 1   closePriceUsd  366 non-null    float64
 2   highPriceUsd   366 non-null    float64
 3   lowPriceUsd    366 non-null    float64
 4   volume         366 non-null    float64
 5   marketcap      366 non-null    float64
dtypes: float64(6)
memory usage: 20.0 KB

In [8]:
bitcoin.describe() # 값이 숫자라면, 여러 통계적인 값을 얻을 수 있다 => 수치형 데이터 요약

,openPriceUsd,closePriceUsd,highPriceUsd,lowPriceUsd,volume,marketcap
count,366.000000,366.000000,366.000000,366.000000,3.660000e+02,3.660000e+02
mean,38925.213675,38856.280957,39768.751576,37928.232550,3.101502e+10,7.365069e+11
std,13236.441651,13265.765947,13534.023938,12957.493017,9.487966e+09,2.484601e+11
min,18826.846797,18837.667712,19358.505722,17718.876793,1.373656e+10,3.606167e+11
25%,24408.376438,24340.205068,25015.083256,23979.967581,2.506113e+10,4.654130e+11
50%,40258.576886,40124.668425,41008.136431,39306.368173,3.036328e+10,7.618296e+11
75%,47235.001916,47227.010725,48096.940308,46328.789246,3.554235e+10,8.926798e+11
max,67464.502924,67566.830088,68744.031364,66382.061008,8.419661e+10,1.274831e+12

In [11]:
data = bitcoin.copy()
data['MA'] = data['closePriceUsd'].rolling(window=5,min_periods=1).mean()
data['trades'] = data['MA'] < data['closePriceUsd']
data['returns'] = data['closePriceUsd'].pct_change()
data['BACKTEST'] = (data['returns'].shift(-1) * data['trades'] + 1).cumprod()

In [12]:
data

,openPriceUsd,closePriceUsd,highPriceUsd,lowPriceUsd,volume,marketcap,MA,trades,returns,BACKTEST
datetime,,,,,,,,,,
2021-09-14 00:00:00+00:00,46732.444869,47092.493833,47213.518594,46210.873623,3.865215e+10,8.860953e+11,47092.493833,False,NaN,1.000000
2021-09-15 00:00:00+00:00,47097.998123,48176.346393,48450.468466,46773.326543,3.048450e+10,9.065325e+11,47634.420113,True,0.023015,0.991843
2021-09-16 00:00:00+00:00,48118.571001,47783.357805,48465.256259,47079.557123,3.176429e+10,8.991792e+11,47684.066010,True,-0.008157,0.981135
2021-09-17 00:00:00+00:00,47771.003108,47267.520023,48155.792481,46854.593267,2.872771e+10,8.895147e+11,47579.929513,False,-0.010795,0.981135
2021-09-18 00:00:00+00:00,47315.576418,48278.363515,48757.321073,47111.398751,2.857563e+10,9.085843e+11,47719.616314,True,0.021386,0.960444
...,...,...,...,...,...,...,...,...,...,...
2022-09-10 00:00:00+00:00,21344.619152,21680.539413,21760.275771,21168.721722,3.691374e+10,4.151175e+11,20103.903758,True,0.014002,0.589385
2022-09-11 00:00:00+00:00,21670.147633,21769.256340,21769.256340,21406.944641,3.449395e+10,4.168403e+11,20690.221483,True,0.004092,0.605662
2022-09-12 00:00:00+00:00,21796.958843,22370.448650,22435.073027,21607.387741,5.021209e+10,4.283740e+11,21306.246438,True,0.027617,0.546466
2022-09-13 00:00:00+00:00,22371.480640,20184.021904,22645.196099,20062.670699,5.213148e+10,3.865236e+11,21477.083832,False,-0.097737,0.546466
2022-09-14 00:00:00+00:00,20187.557956,20364.766932,20465.812965,20122.985642,5.087534e+10,3.899881e+11,21273.806648,False,0.008955,NaN